Installer update
xenserver/xscontainer pull request #36
Opened 2016-10-06 12:31 UTC by thomasmck

Updated install to export daemon.json into D:\ then copy it into the config folder. configure_tls.cmd also now checks if firewall is enabled and asks the user to turn it off if it is.

2016-10-06 13:00 UTC, thomasmck commented on setup.py
> -                                        'data/configure_tls.cmd']},
should 'data/daemon.json' be included in this bit as well?

2016-10-07 10:48 UTC, robertbreker requested changes

2016-10-07 10:48 UTC, robertbreker commented on src/xscontainer/data/configure_tls.cmd
> +xcopy %cdpath%daemon.json %PROGRAMDATA%\docker\config\ || goto :ERRORHANDLER
Should we also do "if not exist...mkdir" before this?
Would rather handle this case, than to see us fail in 2 months because of Docker changes.

2016-10-07 10:48 UTC, robertbreker commented on src/xscontainer/data/configure_tls.cmd
> +echo Please ensure your firewall is turned off
We should ask the users to "Please ensure your firewall allows Docker TLS communication as per the Documentation."

Did you consider checking whether the firewall is enabled? Not loosing sleep about the latter - optional.

2016-10-07 10:48 UTC, robertbreker commented on src/xscontainer/util/tls_cert.py
> +        shutil.rmtree(tempdir)
Can we use tidy the folder and use rmdir here?

2016-10-07 10:48 UTC, robertbreker commented on setup.py
> -                                        'data/configure_tls.cmd']},
yes

2016-10-07 10:48 UTC, robertbreker commented on setup.py
> +                                        'data/configure_tls.cmd', 'data/daemon.json']},
CI Build is failing with ./setup.py:61:80: E501 line too long (87 > 79 characters)

2016-10-07 14:07 UTC, robertbreker approved these changes

2016-10-07 14:08 UTC, merged